/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void idle_task(void);


void init_systick_timer(uint32_t tick_hz);

void init_scheduler_stack(uint32_t sched_top_of_stack);

void init_tasks_stack();

void enable_processor_faults(void);

uint32_t get_psp_value();

__attribute__((naked)) void switch_sp_to_psp();


typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t  current_state;
	void (*task_handler)(void);
}TCB_t;

/* Each task has its own TCB */
TCB_t user_tasks[MAX_TASKS];

uint32_t current_task = 1;

uint32_t global_tick_count = 0;

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	//msp =sp


	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	//psp=sp

	switch_sp_to_psp();

	task1_handler();


    /* Loop forever */
	for(;;);
}

void enable_processor_faults(void){
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR	|= (1 << 18); //usage fault

}



void init_systick_timer(uint32_t tick_hz){

	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;

	uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz) - 1;

	//clear the value
	*pSRVR &= ~(0x00FFFFFF);

	//load the value

	*pSRVR |= count_value;

	//do some setting


	*pSCSR |= (1<<1);
	*pSCSR |= (1<<2);

	//enable systic

	*pSCSR |= (1<<0);

}

uint32_t save_psp_value(uint32_t current_psp_value){

	return user_tasks[current_task].psp_value = current_psp_value;
}

uint32_t get_psp_value(){
	return user_tasks[current_task].psp_value;
}

void update_next_task(void){
	int state = TASK_BLOCKED_STATE;

	for(int i=0; i< (MAX_TASKS);i++){
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if((state == TASK_READY_STATE) && (current_task != 0)){
			break;
		}

	}

	if (state == TASK_BLOCKED_STATE){
		current_task=0;
	}
}


__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){

	__asm volatile("MSR MSP,%0": : "r" (sched_top_of_stack): ); //variable to arm
	__asm volatile("BX LR"); //return from fun call

}

void init_tasks_stack(){

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;

	for(int i=0;i<MAX_TASKS;i++){
		pPSP = (uint32_t*)user_tasks[i].psp_value; // if i =0 it will give the value of T1_STACK_START

		pPSP--; //xpsp
		*pPSP = (uint32_t)DUMMY_XPSR;

		pPSP--; // pc
		*pPSP = (uint32_t)user_tasks[i].task_handler;

		pPSP--; // LR
		*pPSP = 0xFFFFFFFD;

		for(int j=0;j<13;j++){
			pPSP--;
			*pPSP=0;
		}

		user_tasks[i].psp_value=(uint32_t)pPSP;



	}

}

void update_global_tick_count(void)
{
	global_tick_count++;
}


void unblock_tasks(void)
{
	for(int i = 1 ; i < MAX_TASKS ; i++)
	{
		if(user_tasks[i].current_state != TASK_READY_STATE)
		{
			if(global_tick_count >= user_tasks[i].block_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}

	}

}


void  SysTick_Handler(void)
{

	uint32_t *pICSR = (uint32_t*)0xE000ED04;

    update_global_tick_count();

    unblock_tasks();

    //pend the pendsv exception
    *pICSR |= ( 1 << 28);
}


__attribute__((naked)) void PendSV_Handler(void){
	//saving current contex
	__asm volatile ("MRS R0,PSP"); // CURRENT PSP ->  R0

	__asm volatile ("STMDB R0!,{R4-R11}"); //STORE THE VALUE R4-R11 to R0 AND RETUTRE THE LAST ADDRESS TO R0

	__asm volatile ("PUSH {LR}");

	__asm volatile ("BL save_psp_value"); //store current psp



	//retriving the nxt contex

	__asm volatile("BL update_next_task"); // decide next task to run

	__asm volatile("BL get_psp_value"); 	// get its last psp value

	__asm volatile("LDMIA R0!,{R4-R11}");	// retrive value in r4-r11

	__asm volatile("MSR PSP,R0"); // UPDATE PSP AND EXIT

	__asm volatile ("POP {LR}");

	__asm volatile ("BX LR");

}

void schedule(void){
	//pending pendsv
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= (1 << 28);
}

void task_delay(uint32_t ticks){


	if (current_task){
		user_tasks[current_task].block_count = global_tick_count + ticks;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}


}

void HardFault_Handler(void){
	printf("Exception: Hardfault\n");
	while(1);
}


void MemManage_Handler(void){
	printf("Exception: MemManage\n");
	while(1);
}
void BusFault_Handler(void){
	printf("Exception: BusFault\n");
	while(1);
}




__attribute__((naked)) void switch_sp_to_psp(){
	//init psp with task1 stack start



	//get the value of psp of current

	__asm volatile ("PUSH {LR}");//preserve lr because it is going back to main
	__asm volatile ("BL get_psp_value");
	__asm volatile ("MSR PSP,R0");
	__asm volatile ("POP {LR}");

	//change sp to psp
	__asm volatile ("MOV R0,0x02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");


}


void idle_task(void){
	while(1){}

}


void task1_handler(void)
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}

}

void task2_handler(void)
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}

}

void task3_handler(void)
{
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}

}

void task4_handler(void)

{
	while(1)
	{
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}


}
